name: Beta Release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+-*'

jobs:
  beta-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upgrade setuptools/build
        run: |
          pip3 install wheel --upgrade
          pip3 install setuptools --upgrade

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Release to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

        run: |
          python -m pip install --upgrade build
          python -m build .
          python -m pip install --upgrade twine
          twine upload --repository testpypi dist/*
