name: CI

on:
  push:
    branches: [ master, develop, vb/pyright ]
  pull_request:
    branches: [ master, develop, vb/pyright ]

jobs:
  run_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade setuptools
        run: |
          pip3 install wheel --upgrade
          pip3 install setuptools --upgrade

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install cryoDRGN with dev dependencies
        run: |
          python -m pip install .[dev]

      - name: Pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Pyright
        run: |
          pyright

      - name: Pytest
        run: |
          pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
